### ISSUE TITLE
Needs rop3ds to compile.

### ISSUE THREAD

**Issue by CrimsonMaple** [Pixilate/Reinand-Plus-RE#1]
Please just replace the CakeHax and CakeBrah with recursive git clones. Yes rop is unused but ReiNand needs it to compile. That's why I left it in my fork

**Comment by RomLecat** [comment]
Agreed. I can't build it because it complains about missing rop3ds.

**Comment by CrimsonMaple** [comment]
For all of you trying to compile at home. Delete CakeHax and use the git command: git clone --recursive https://github.com/mid-kid/CakeHax.git

**Comment by RomLecat** [comment]
Seems to fix the rop error, but I still can't build it. I get a "source/fsldr.c:4:20: fatal error: srvsys.h: No such file or directory", not sure if it's related or not.

**Comment by CrimsonMaple** [comment]
Do you have spaces in the file directory?

**Comment by RomLecat** [comment]
No, the absolute path is /var/lib/jenkins/workspace/3DS/ReiNAND+. I'll try without the "+".

EDIT : Hmm, still nothing. Same error...

**Comment by Pixilate** [comment]
I'll update cakehax  right now, was doing something heh

**Comment by CrimsonMaple** [comment]
Ahh Unix. I think I know the issue.

**Comment by CrimsonMaple** [comment]
Also need libkhax in CakeBrah lol forgot that. Fix do the same command as above with CakeBrah.git instead of CakeHax.git

**Comment by Pixilate** [comment]
![image](https://cloud.githubusercontent.com/assets/12451040/22000487/5b3b3210-dc0d-11e6-91a6-762fb84cc092.png)
I seem to get the error as well. This takes me back to me messing with it :P 
gonna fix the loader

**Comment by CrimsonMaple** [comment]
Do you have MakeRom in DevkitPro?

**Comment by Pixilate** [comment]
of course

**Comment by CrimsonMaple** [comment]
Weird. Gimme a few. Idk if it will work but i have a theory

**Comment by Pixilate** [comment]
I'll look into it as well

**Comment by Pixilate** [comment]
well shit

**Comment by Pixilate** [comment]
A huge portion of the loader is gone. I'll fix that

**Comment by Pixilate** [comment]
@Hakujou I've fixed the loader

**Comment by RomLecat** [comment]
It's working now ! By the way, feel free to use my Jenkins builds if you need it : https://jenkins.hakujou.fr/job/3DS/job/ReiNAND+/

**Comment by CrimsonMaple** [comment]
Cool, i also may have fixed a loader naming issue. I added a quick addition to the makefile under the loader.cxi section.
