### ISSUE TITLE
Add Settings version string

### ISSUE THREAD

**Issue by gnmmarechal** [Pixilate/Reinand-Plus-RE#2]
Unless I'm mistaken, ReiNand doesn't have this, correct? It'd be cool to have imo.

**Comment by Pixilate** [comment]
ReiNand does have it, but with all the changes I'm planning to do to the loader, it is not a priority.

**Comment by gnmmarechal** [comment]
It may not be a priority, but you could tag it as an enhancement and do it later, I suppose.

Or not.
